# Generated by Django 4.2.6 on 2025-01-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MALANRawResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, null=True)),
                ('last_updated', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('aid_type', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('animals', models.TextField(blank=True, null=True)),
                ('volunteers_needs', models.TextField(blank=True, null=True)),
                ('accepting', models.TextField(blank=True, null=True)),
                ('providing', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('closed', models.BooleanField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
