# Generated by Django 4.2.6 on 2025-01-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django_orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedHelpResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('aid_type', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('providing', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WantToHelpResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('aid_type', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('volunteers_needs', models.TextField(blank=True, null=True)),
                ('accepting', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
