# Generated by Django 4.2.6 on 2025-01-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django_orm', '0002_needhelpresource_wanttohelpresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanttohelpresource',
            name='last_updated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='needhelpresource',
            name='last_updated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
